pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:ShulanX/dnananopore.git
          - cd dnananopore.git
          - git push --mirror git@github.com:shulanx1/dnananopore.git
